# Site settings
title: Evolute
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nyutka.github.io/evolute/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems: [jekyll-paginate]
paginate: 2
paginate_path: /blog/page:num/
